CREATE TABLE estoques
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    produto_id BIGINT                                  NOT NULL,
    quantidade INTEGER                                 NOT NULL,
    CONSTRAINT pk_estoques PRIMARY KEY (id)
);

ALTER TABLE estoques
    ADD CONSTRAINT uc_estoques_produto UNIQUE (produto_id);

ALTER TABLE estoques
    ADD CONSTRAINT FK_ESTOQUES_ON_PRODUTO FOREIGN KEY (produto_id) REFERENCES produtos (id);