CREATE TABLE vendas
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    data        TIMESTAMP(6) WITHOUT TIME ZONE          NOT NULL,
    valor_total DECIMAL                                 NOT NULL,
    CONSTRAINT pk_vendas PRIMARY KEY (id)
);